### ISSUE TITLE
sio_name incorrect on amazon ec2

### ISSUE THREAD

**Issue by cholcombe973** [emccode/juju-scaleio#2]
When trying to deploy the mds cluster on amazon it failed with an error about the sio_name being incorrect.  
`hooks/scaleio-sds-relation-changed:  sio_name=>'$remote_name', ips=>'$ips', ip_roles=>'$ip_roles', protection_domain=>'$protection_domain', \
`
I can try and deploy it again later today and get the exact error but this might point you in the right direction.
I was deploying these on m2 mediums.  Nothing special

**Comment by Andrey-mp** [comment]
Hi,
It happened because charms was got from our master branch but master charms take puppets from release tag.

So for consistency charms should be taken from release tag or charmstore (https://jujucharms.com/u/cloudscaling/)

We've made needed changes for next update - charms from master will use updates' puppets and new puppets are uploaded to puppet forge.
